INSERT INTO menu_items (name, description, price, category) VALUES
('House Blend', 'Our signature blend of medium roast coffee', 4.50, 'coffee'),
('Ethiopian Single Origin', 'Fruity and floral notes from Yirgacheffe', 5.50, 'coffee'),
('Colombian Supremo', 'Smooth and balanced with nutty undertones', 5.00, 'coffee'),
('Cold Brew', 'Slow-steeped for 18 hours, smooth and bold', 4.75, 'coffee'),
('Breakfast Blend', 'Light roast perfect for mornings', 4.25, 'coffee'),
('Cappuccino', 'Espresso with steamed milk foam', 5.00, 'espresso'),
('Latte', 'Espresso with steamed milk', 5.25, 'espresso'),
('Americano', 'Espresso with hot water', 4.00, 'espresso'),
('Caramel Macchiato', 'Espresso with caramel and vanilla', 5.75, 'espresso'),
('Flat White', 'Double espresso with microfoam', 5.50, 'espresso'),
('Espresso Shot', 'Double shot of rich espresso', 3.50, 'espresso'),
('Matcha Latte', 'Green tea powder with steamed milk', 5.50, 'tea'),
('Earl Grey', 'Classic black tea with bergamot', 3.50, 'tea'),
('Chai Latte', 'Spiced tea with steamed milk', 5.00, 'tea'),
('Green Tea', 'Japanese sencha green tea', 3.25, 'tea'),
('Croissant', 'Buttery, flaky French pastry', 3.50, 'pastry'),
('Blueberry Muffin', 'Fresh baked with real blueberries', 3.25, 'pastry'),
('Chocolate Chip Cookie', 'Warm, gooey cookie', 2.50, 'pastry'),
('Scone', 'Fresh baked scone with jam', 4.00, 'pastry'),
('Bagel with Cream Cheese', 'Fresh bagel with cream cheese', 3.75, 'pastry'),
('Brownie', 'Rich chocolate brownie', 3.25, 'pastry');
